### ISSUE TITLE
update to Laravel 5.6

### ISSUE THREAD

**Issue by Rasoul-Karimi** [cybercog/laravel-optimus#12]
hi 
i have a problem when i want to update laravel from 5.5. to 5.6 and get this error:

` Problem 1
    - Conclusion: remove cybercog/laravel-optimus 2.1.0
    - Conclusion: don't install laravel/framework v5.6.5
    - Conclusion: don't install laravel/framework v5.6.4
    - Conclusion: don't install laravel/framework v5.6.3
    - Conclusion: don't install laravel/framework v5.6.2
    - Installation request for cybercog/laravel-optimus ^2.1 -> satisfiable by cybercog/laravel-optimus[2.1.0].
    - Conclusion: don't install laravel/framework v5.6.1
    - cybercog/laravel-optimus 2.1.0 requires graham-campbell/manager ^3.0 -> satisfiable by graham-campbell/manager[v3.0.0].
    - graham-campbell/manager v3.0.0 requires illuminate/support 5.1.*|5.2.*|5.3.*|5.4.*|5.5.* -> satisfiable by laravel/framework[v5.5.35], illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35].
    - graham-campbell/manager v3.0.0 requires illuminate/support 5.1.*|5.2.*|5.3.*|5.4.*|5.5.* -> satisfiable by laravel/framework[v5.5.35], illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35].`

**Comment by a-komarev** [comment]
For Laravel 5.6 you should use Laravel Optimus v3. It's required because Laravel Manager dependency dropped all PHP support lower than 7.1.3. Laravel 5.5 and below will be maintained in 2.x versions.

**Comment by a-komarev** [comment]
I suppose this issue was resolved. If there are any other issues related to upgrade process - feel free to continue conversation or open a new one.

**Comment by Rasoul-Karimi** [comment]
yes, i use version ^3.0  and this was resolved. Thanks
