### ISSUE TITLE
Update to Laravel 10

### ISSUE THREAD

**Issue by vonec** [cybercog/laravel-optimus#34]
Can you update this package to support laravel 10

**Comment by antonkomarev** [comment]
Duplicate #33
Plan to work on it today

**Comment by antonkomarev** [comment]
We need to wait this PR of the dependency to be merged:
- https://github.com/GrahamCampbell/Laravel-Manager/pull/18

After that we can add Laravel v10 support.

PR to add Laravel v10 support:
- #35
